### ISSUE TITLE
avahi-sys crate is LGPL

### ISSUE THREAD

**Issue by yamadapc** [windy1/zeroconf-rs#19]
There's a dependency to this crate, `avahi-sys` which is set with the LGPL license.

https://github.com/windy1/avahi-sys

**Comment by windy1** [comment]
From LGPL

> A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.
