### ISSUE TITLE
Question: how are name collisions handled?

### ISSUE THREAD

**Issue by bmulder-innoseis** [windy1/zeroconf-rs#20]
I want to be able to publish multiple instances of the same service running in the network on different hosts.
In avahi, there is a specific way to handle collision errors, and a default way to change the name (calling `avahi_alternative_service_name`, works by appending "#1", "#2", etc.)
How is this done in this library?

**Comment by windy1** [comment]
This is not currently handled, please feel free to open a pull request with an integration of `avahi_alternative_service_name` and some Bonjour equivalent

**Comment by windy1** [comment]
This has been a long time coming but I've started to implement this in #40

I'm having some trouble actually triggering a name collision in Avahi while testing. Is this something you had experience with? Thanks.

**Comment by windy1** [comment]
Resolved in https://github.com/windy1/zeroconf-rs/pull/40
