### ISSUE TITLE
'could not register service' on MacOS

### ISSUE THREAD

**Issue by makononov** [windy1/zeroconf-rs#7]
When attempting to execute the demo code on MacOS 11.2:
```
    // Advertise node
    let mut service = MdnsService::new("_myservice._tcp.local", 8080);
    let mut txt_record = TxtRecord::new();
    let context: Arc<Mutex<Context>> = Arc::default();
    txt_record.insert("pubkey", cert.serialize_pem().as_str()).unwrap();

    service.set_txt_record(txt_record);
    service.set_context(Box::new(context));
    service.set_registered_callback(Box::new(callback));

    let event_loop = service.register().unwrap();

    loop {
        event_loop.poll(Duration::from_secs(10)).unwrap();
    }
```

I get the following error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "could not register service (code: -65540)" }', src/main.rs:38:41
```

Looks like `-65540` might be being caused by a bad parameter in Bonjour? I'm happy to help debug, if you can point me in the right direction. Thanks!

**Comment by windy1** [comment]
Hi there, I'm not able to reproduce this. What version of zeroconf are you using? And you are correct, that code does indicate a bad param.

**Comment by makononov** [comment]
I was using `zeroconf = "^0.7"` but just changed it to the git repo with the same results. I just copy/pasted the example code and it works as expected, so this must be something on my end. I'll close this ticket and reopen if I determine it's actually a bug. Thanks!

**Comment by windy1** [comment]
Ah I believe it might be the `.local` on your service there. I don't think thats a valid format.

**Comment by makononov** [comment]
Good eye, it looks like that's what was doing it. Thanks for the assistance!
